### ISSUE TITLE
fix for LocalizedControlType problem and to get url from edit

### ISSUE THREAD

**Issue by FilRav** [progietheus/Google-Chrome-URL-Check-C-Sharp#1]
Theese are the change I needed to make to let this useful class works:

1. Change:
if (elementNode.Current.ControlType.LocalizedControlType == "edit")
with:
if (elementNode.Current.ControlType.ProgrammaticName == "ControlType.Edit")
otherwise it's language-dependent (and it doesn't work for languages different from english).

2. Change:
var result = ((ValuePattern)elmUrlBar.GetCurrentPattern(patterns[0])).Current.Value;
with:
var result = ((ValuePattern)elmUrlBar.GetCurrentPattern(ValuePattern.Pattern)).Current.Value;

Good work!

**Comment by FilRav** [comment]
I've also removed the following lines (otherwise doesn't work on .net 3.5):
using static System.Windows.Automation.AutomationElement;
using System.Threading.Tasks;

References needed: UIAutomationClient and UIAutomationTypes

**Comment by progietheus** [comment]
Thank you for making these adjustments @FilRav ! 👍 

Feel free to create a PR and I’ll merge them into the project, otherwise I will try to make these changes as soon as possible.

**Comment by SoaresMG** [comment]
Did this PR got merged?

**Comment by progietheus** [comment]
I believe I did merge it, It was my first PR though, so I may have done it wrong. But pretty sure it went through! Check commit history, currently not at a computer.
